AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-00c6177f250e07ec1
      InstanceType: t2.micro
  
